import image0 from "@/assets/catalogue/prod-armoire.asset.json";
import image1 from "@/assets/catalogue/prod-aspirateur.asset.json";
import image2 from "@/assets/catalogue/prod-canape-3-places.asset.json";
import image3 from "@/assets/catalogue/prod-chauffe-eau.asset.json";
import image4 from "@/assets/catalogue/prod-climatiseur-split.asset.json";
import image5 from "@/assets/catalogue/prod-commode.asset.json";
import image6 from "@/assets/catalogue/prod-cuisiniere-4-feux.asset.json";
import image7 from "@/assets/catalogue/prod-four-encastrable.asset.json";
import image8 from "@/assets/catalogue/prod-lave-linge-frontal.asset.json";
import image9 from "@/assets/catalogue/prod-lave-vaisselle.asset.json";
import image10 from "@/assets/catalogue/prod-lit-double.asset.json";
import image11 from "@/assets/catalogue/prod-meuble-tv.asset.json";
import image12 from "@/assets/catalogue/prod-micro-ondes.asset.json";
import image13 from "@/assets/catalogue/prod-refrigerateur-americain.asset.json";
import image14 from "@/assets/catalogue/prod-refrigerateur-combine.asset.json";
import image15 from "@/assets/catalogue/prod-robot-cuisine.asset.json";
import image16 from "@/assets/catalogue/prod-salon-angle.asset.json";
import image17 from "@/assets/catalogue/prod-salon-marocain.asset.json";
import image18 from "@/assets/catalogue/prod-table-salle-a-manger.asset.json";
import image19 from "@/assets/catalogue/prod-tv-55.asset.json";
import type { Product } from "./types";

// Public catalogue snapshot from belleimage.izemxlab.com (07/10/2026).
export const CLIENT_CATALOGUE: Product[] = [
  {
    "id": "p1",
    "ref": "BI-1000",
    "name": "Réfrigérateur combiné No Frost 350 L",
    "nameAr": "",
    "brand": "Bosch",
    "category": "Électroménager",
    "sub": "Réfrigérateurs",
    "price": 6499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Réfrigérateur combiné No Frost 350 L (350 L · No Frost · A+). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image14.url
  },
  {
    "id": "p2",
    "ref": "BI-1001",
    "name": "Réfrigérateur combiné 450 L inox",
    "nameAr": "",
    "brand": "Samsung",
    "category": "Électroménager",
    "sub": "Réfrigérateurs",
    "price": 8999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Réfrigérateur combiné 450 L inox (450 L · No Frost · A++). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image14.url
  },
  {
    "id": "p3",
    "ref": "BI-1002",
    "name": "Réfrigérateur américain 600 L",
    "nameAr": "",
    "brand": "Candy",
    "category": "Électroménager",
    "sub": "Réfrigérateurs",
    "price": 15999,
    "stock": 2,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Réfrigérateur américain 600 L (600 L · Distributeur d'eau). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image13.url
  },
  {
    "id": "p4",
    "ref": "BI-1003",
    "name": "Congélateur coffre 300 L",
    "nameAr": "",
    "brand": "Taurus",
    "category": "Électroménager",
    "sub": "Réfrigérateurs",
    "price": 4299,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Congélateur coffre 300 L (300 L · Coffre). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image14.url
  },
  {
    "id": "p5",
    "ref": "BI-1004",
    "name": "Réfrigérateur double porte 250 L",
    "nameAr": "",
    "brand": "Kröhler",
    "category": "Électroménager",
    "sub": "Réfrigérateurs",
    "price": 3999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Réfrigérateur double porte 250 L (250 L · Double porte). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image14.url
  },
  {
    "id": "p6",
    "ref": "BI-1005",
    "name": "Lave-linge hublot 8 kg",
    "nameAr": "",
    "brand": "Schleizer",
    "category": "Électroménager",
    "sub": "Lave-linge",
    "price": 4999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Lave-linge hublot 8 kg (8 kg · 1400 tr/min · A+++). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image8.url
  },
  {
    "id": "p7",
    "ref": "BI-1006",
    "name": "Lave-linge hublot 10 kg Inverter",
    "nameAr": "",
    "brand": "Siera",
    "category": "Électroménager",
    "sub": "Lave-linge",
    "price": 6999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Lave-linge hublot 10 kg Inverter (10 kg · Moteur Inverter). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image8.url
  },
  {
    "id": "p8",
    "ref": "BI-1007",
    "name": "Lavante-séchante 9/6 kg",
    "nameAr": "",
    "brand": "Tivoli",
    "category": "Électroménager",
    "sub": "Lave-linge",
    "price": 8499,
    "stock": 2,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Lavante-séchante 9/6 kg (9 kg lavage · 6 kg séchage). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image8.url
  },
  {
    "id": "p9",
    "ref": "BI-1008",
    "name": "Lave-linge hublot 7 kg",
    "nameAr": "",
    "brand": "Bosch",
    "category": "Électroménager",
    "sub": "Lave-linge",
    "price": 3799,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Lave-linge hublot 7 kg (7 kg · 1200 tr/min). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image8.url
  },
  {
    "id": "p10",
    "ref": "BI-1009",
    "name": "Lave-vaisselle 14 couverts",
    "nameAr": "",
    "brand": "Samsung",
    "category": "Électroménager",
    "sub": "Lave-linge",
    "price": 5299,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Lave-vaisselle 14 couverts (14 couverts · 6 programmes). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image9.url
  },
  {
    "id": "p11",
    "ref": "BI-1010",
    "name": "Lave-vaisselle 12 couverts",
    "nameAr": "",
    "brand": "Candy",
    "category": "Électroménager",
    "sub": "Lave-linge",
    "price": 3999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Lave-vaisselle 12 couverts (12 couverts · 5 programmes). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image9.url
  },
  {
    "id": "p12",
    "ref": "BI-1011",
    "name": "Cuisinière 5 feux 90 cm",
    "nameAr": "",
    "brand": "Taurus",
    "category": "Électroménager",
    "sub": "Cuisson",
    "price": 4599,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Cuisinière 5 feux 90 cm (5 feux gaz · Four 110 L). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image6.url
  },
  {
    "id": "p13",
    "ref": "BI-1012",
    "name": "Cuisinière 4 feux 60 cm",
    "nameAr": "",
    "brand": "Kröhler",
    "category": "Électroménager",
    "sub": "Cuisson",
    "price": 2999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Cuisinière 4 feux 60 cm (4 feux gaz · Four 60 L). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image6.url
  },
  {
    "id": "p14",
    "ref": "BI-1013",
    "name": "Four encastrable multifonction",
    "nameAr": "",
    "brand": "Schleizer",
    "category": "Électroménager",
    "sub": "Cuisson",
    "price": 3499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Four encastrable multifonction (70 L · 8 fonctions). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image7.url
  },
  {
    "id": "p15",
    "ref": "BI-1014",
    "name": "Plaque de cuisson gaz 5 feux",
    "nameAr": "",
    "brand": "Siera",
    "category": "Électroménager",
    "sub": "Cuisson",
    "price": 1899,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Plaque de cuisson gaz 5 feux (Verre trempé · 5 feux). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image6.url
  },
  {
    "id": "p16",
    "ref": "BI-1015",
    "name": "Smart TV 55\" 4K UHD",
    "nameAr": "",
    "brand": "Tivoli",
    "category": "Électroménager",
    "sub": "TV & image",
    "price": 5499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Smart TV 55\" 4K UHD (55\" · 4K · HDR). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image19.url
  },
  {
    "id": "p17",
    "ref": "BI-1016",
    "name": "Smart TV 43\" Full HD",
    "nameAr": "",
    "brand": "Bosch",
    "category": "Électroménager",
    "sub": "TV & image",
    "price": 2999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Smart TV 43\" Full HD (43\" · Full HD · Wi-Fi). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image19.url
  },
  {
    "id": "p18",
    "ref": "BI-1017",
    "name": "Smart TV 65\" 4K QLED",
    "nameAr": "",
    "brand": "Samsung",
    "category": "Électroménager",
    "sub": "TV & image",
    "price": 9999,
    "stock": 2,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Smart TV 65\" 4K QLED (65\" · 4K · QLED). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image19.url
  },
  {
    "id": "p19",
    "ref": "BI-1018",
    "name": "Smart TV 75\" 4K",
    "nameAr": "",
    "brand": "Candy",
    "category": "Électroménager",
    "sub": "TV & image",
    "price": 14999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Smart TV 75\" 4K (75\" · 4K · Dolby). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image19.url
  },
  {
    "id": "p20",
    "ref": "BI-1019",
    "name": "Climatiseur split 12 000 BTU",
    "nameAr": "",
    "brand": "Taurus",
    "category": "Électroménager",
    "sub": "Climatisation",
    "price": 4299,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Climatiseur split 12 000 BTU (12 000 BTU · Chaud/froid). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image4.url
  },
  {
    "id": "p21",
    "ref": "BI-1020",
    "name": "Climatiseur Inverter 18 000 BTU",
    "nameAr": "",
    "brand": "Kröhler",
    "category": "Électroménager",
    "sub": "Climatisation",
    "price": 6999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Climatiseur Inverter 18 000 BTU (18 000 BTU · Inverter A++). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image4.url
  },
  {
    "id": "p22",
    "ref": "BI-1021",
    "name": "Climatiseur Inverter 24 000 BTU",
    "nameAr": "",
    "brand": "Schleizer",
    "category": "Électroménager",
    "sub": "Climatisation",
    "price": 8999,
    "stock": 2,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Climatiseur Inverter 24 000 BTU (24 000 BTU · Inverter). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image4.url
  },
  {
    "id": "p23",
    "ref": "BI-1022",
    "name": "Chauffe-eau électrique 80 L",
    "nameAr": "",
    "brand": "Siera",
    "category": "Électroménager",
    "sub": "Climatisation",
    "price": 1899,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Chauffe-eau électrique 80 L (80 L · Thermostat réglable). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image3.url
  },
  {
    "id": "p24",
    "ref": "BI-1023",
    "name": "Chauffe-eau à gaz 10 L",
    "nameAr": "",
    "brand": "Tivoli",
    "category": "Électroménager",
    "sub": "Climatisation",
    "price": 1599,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Chauffe-eau à gaz 10 L (10 L/min · Allumage automatique). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image3.url
  },
  {
    "id": "p25",
    "ref": "BI-1024",
    "name": "Blender chauffant 1,7 L",
    "nameAr": "",
    "brand": "Bosch",
    "category": "Électroménager",
    "sub": "Petit électroménager",
    "price": 899,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Blender chauffant 1,7 L (1,7 L · 1200 W). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image15.url
  },
  {
    "id": "p26",
    "ref": "BI-1025",
    "name": "Robot pâtissier 5 L",
    "nameAr": "",
    "brand": "Samsung",
    "category": "Électroménager",
    "sub": "Petit électroménager",
    "price": 1999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Robot pâtissier 5 L (5 L · 1000 W). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image15.url
  },
  {
    "id": "p27",
    "ref": "BI-1026",
    "name": "Aspirateur traîneau sans sac",
    "nameAr": "",
    "brand": "Candy",
    "category": "Électroménager",
    "sub": "Petit électroménager",
    "price": 1299,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Aspirateur traîneau sans sac (2000 W · Sans sac). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image1.url
  },
  {
    "id": "p28",
    "ref": "BI-1027",
    "name": "Micro-ondes grill 25 L",
    "nameAr": "",
    "brand": "Taurus",
    "category": "Électroménager",
    "sub": "Petit électroménager",
    "price": 1099,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 24,
    "description": "Micro-ondes grill 25 L (25 L · Grill). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 2,
    "imageUrl": image12.url
  },
  {
    "id": "p29",
    "ref": "BI-1028",
    "name": "Canapé d'angle 5 places",
    "nameAr": "",
    "brand": "Kröhler",
    "category": "Ameublement",
    "sub": "Salons",
    "price": 8999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Canapé d'angle 5 places (5 places · Tissu). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image16.url
  },
  {
    "id": "p30",
    "ref": "BI-1029",
    "name": "Canapé 3 places velours",
    "nameAr": "",
    "brand": "Schleizer",
    "category": "Ameublement",
    "sub": "Salons",
    "price": 5499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Canapé 3 places velours (3 places · Velours). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image2.url
  },
  {
    "id": "p31",
    "ref": "BI-1030",
    "name": "Salon marocain moderne 8 places",
    "nameAr": "",
    "brand": "Siera",
    "category": "Ameublement",
    "sub": "Salons",
    "price": 14999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Salon marocain moderne 8 places (8 places · Sur mesure). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image17.url
  },
  {
    "id": "p32",
    "ref": "BI-1031",
    "name": "Fauteuil relax",
    "nameAr": "",
    "brand": "Tivoli",
    "category": "Ameublement",
    "sub": "Salons",
    "price": 2499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Fauteuil relax (1 place · Simili cuir). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image2.url
  },
  {
    "id": "p33",
    "ref": "BI-1032",
    "name": "Fauteuil d'appoint scandinave",
    "nameAr": "",
    "brand": "Bosch",
    "category": "Ameublement",
    "sub": "Salons",
    "price": 1499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Fauteuil d'appoint scandinave (Pieds bois · Tissu). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image2.url
  },
  {
    "id": "p34",
    "ref": "BI-1033",
    "name": "Chambre à coucher complète",
    "nameAr": "",
    "brand": "Samsung",
    "category": "Ameublement",
    "sub": "Chambres",
    "price": 13999,
    "stock": 2,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Chambre à coucher complète (Lit 160 · Armoire · 2 chevets). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image10.url
  },
  {
    "id": "p35",
    "ref": "BI-1034",
    "name": "Lit double 160×200 capitonné",
    "nameAr": "",
    "brand": "Candy",
    "category": "Ameublement",
    "sub": "Chambres",
    "price": 3999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Lit double 160×200 capitonné (160×200 · Tête capitonnée). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image10.url
  },
  {
    "id": "p36",
    "ref": "BI-1035",
    "name": "Matelas mousse haute densité",
    "nameAr": "",
    "brand": "Taurus",
    "category": "Ameublement",
    "sub": "Chambres",
    "price": 2299,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Matelas mousse haute densité (Épaisseur 25 cm). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image10.url
  },
  {
    "id": "p37",
    "ref": "BI-1036",
    "name": "Lit enfant 90×190",
    "nameAr": "",
    "brand": "Kröhler",
    "category": "Ameublement",
    "sub": "Chambres",
    "price": 1799,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Lit enfant 90×190 (90×190 · Avec tiroir). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image10.url
  },
  {
    "id": "p38",
    "ref": "BI-1037",
    "name": "Table à manger 6 places",
    "nameAr": "",
    "brand": "Schleizer",
    "category": "Ameublement",
    "sub": "Salles à manger",
    "price": 3499,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Table à manger 6 places (6 places · Plateau verre). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image18.url
  },
  {
    "id": "p39",
    "ref": "BI-1038",
    "name": "Ensemble table + 8 chaises",
    "nameAr": "",
    "brand": "Siera",
    "category": "Ameublement",
    "sub": "Salles à manger",
    "price": 7999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Ensemble table + 8 chaises (8 places · Bois massif). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image18.url
  },
  {
    "id": "p40",
    "ref": "BI-1039",
    "name": "Table extensible 4–8 places",
    "nameAr": "",
    "brand": "Tivoli",
    "category": "Ameublement",
    "sub": "Salles à manger",
    "price": 4999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Table extensible 4–8 places (Extensible · Bois). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image18.url
  },
  {
    "id": "p41",
    "ref": "BI-1040",
    "name": "Armoire 3 portes miroir",
    "nameAr": "",
    "brand": "Bosch",
    "category": "Ameublement",
    "sub": "Rangement",
    "price": 4299,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Armoire 3 portes miroir (3 portes · Miroir central). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image0.url
  },
  {
    "id": "p42",
    "ref": "BI-1041",
    "name": "Armoire 2 portes coulissantes",
    "nameAr": "",
    "brand": "Samsung",
    "category": "Ameublement",
    "sub": "Rangement",
    "price": 3499,
    "stock": 2,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Armoire 2 portes coulissantes (2 portes coulissantes). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image0.url
  },
  {
    "id": "p43",
    "ref": "BI-1042",
    "name": "Meuble TV 180 cm",
    "nameAr": "",
    "brand": "Candy",
    "category": "Ameublement",
    "sub": "Rangement",
    "price": 1999,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Meuble TV 180 cm (180 cm · LED). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image11.url
  },
  {
    "id": "p44",
    "ref": "BI-1043",
    "name": "Commode 6 tiroirs",
    "nameAr": "",
    "brand": "Taurus",
    "category": "Ameublement",
    "sub": "Rangement",
    "price": 1599,
    "stock": 12,
    "threshold": 3,
    "location": "Magasin",
    "status": "Actif",
    "warrantyMonths": 12,
    "description": "Commode 6 tiroirs (6 tiroirs). Disponible chez Belle Image à Kénitra, livré chez vous et payable à la livraison.",
    "deliveryDays": 5,
    "imageUrl": image5.url
  }
];
