/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProduitsRouteImport } from './routes/produits'
import { Route as CommandesIndexRouteImport } from './routes/commandes.index'
import { Route as CommandesIdRouteImport } from './routes/commandes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsRoute = ProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesIndexRoute = CommandesIndexRouteImport.update({
  id: '/commandes/',
  path: '/commandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesIdRoute = CommandesIdRouteImport.update({
  id: '/commandes/$id',
  path: '/commandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/produits': typeof ProduitsRoute
  '/commandes/$id': typeof CommandesIdRoute
  '/commandes/': typeof CommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/produits': typeof ProduitsRoute
  '/commandes/$id': typeof CommandesIdRoute
  '/commandes': typeof CommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/produits': typeof ProduitsRoute
  '/commandes/$id': typeof CommandesIdRoute
  '/commandes/': typeof CommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/produits' | '/commandes/$id' | '/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/produits' | '/commandes/$id' | '/commandes'
  id:
    '__root__' | '/' | '/login' | '/produits' | '/commandes/$id' | '/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProduitsRoute: typeof ProduitsRoute
  CommandesIdRoute: typeof CommandesIdRoute
  CommandesIndexRoute: typeof CommandesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits': {
      id: '/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof ProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/': {
      id: '/commandes/'
      path: '/commandes'
      fullPath: '/commandes/'
      preLoaderRoute: typeof CommandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/$id': {
      id: '/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/commandes/$id'
      preLoaderRoute: typeof CommandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProduitsRoute: ProduitsRoute,
  CommandesIdRoute: CommandesIdRoute,
  CommandesIndexRoute: CommandesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
